### ISSUE TITLE
Using create_table_if_not_exists reaches unreachable code

### ISSUE THREAD

**Issue by mbilker** [spacekookie/barrel#45]
When running `create_table_if_not_exists`, it pushes the `DatabaseChange` to the changes array, but then immediately gets the last element and matches to see if it's `CreateTable`, which it never will be.

https://github.com/spacekookie/barrel/blob/c78e091ff8172e9ac0c6f77ce2b8bf9dc853bb05/src/migration.rs#L132-L149

**Comment by ELD** [comment]
I have also experienced this issue, but I haven't traced through the code enough to find the intended fix.

Definitely would be a worthy thing to fix up so the method can be used.

**Comment by rippinrobr** [comment]
I have also hit that issue in the past but I haven't been able to reliably reproduce it.

**Comment by spacekookie** [comment]
Oof, yea this issue has come up before. It makes me feel like we definitely need more and better tests to reproduce this.

**Comment by rippinrobr** [comment]
This code reproduces it. I'll try and see why now. 

```
use barrel::backend::Pg;
use barrel::types;
use barrel::*;


#[derive(Clone, Debug)]
pub struct ColumnDef{
    pub name: String,
    pub data_type: String,
}

fn main() {
    let columns: Vec<ColumnDef> = vec![ ColumnDef { name: String::from("col1"), data_type: String::from("varchar(32)") } ];

    let mut m = Migration::new();
    let cols = columns.clone();
    m.create_table_if_not_exists("my_table", move |t| {
      for col in cols.clone() {
        println!("{:?}", col);
        let cname: &str = &col.name;
        t.add_column(cname, types::varchar(255));
      }
    }).without_id();

    println!("{}", m.make::<Pg>());
}
```

My `Cargo.toml` file
```
[package]
name = "test-barrel-unreachable"
version = "0.1.0"
authors = ["Rob Rowe <rippinrobr@gmail.com>"]
edition = "2018"

[dependencies]
barrel = { version = "0.5.0-rc.1", features = ["pg"] }
postgres = "0.15.2"
```

**Comment by ELD** [comment]
@rippinrobr The method that was posted in the original comment (`create_table_if_not_exists`) always results in the `match` reaching `unreachable!()` because the first match arm is likely the incorrect `DatabaseChange` variant. It matches a `DatabaseChange::CreateTable(..)` instead of a `DatabaseChange::CreateTableIfNotExists(..)`.

That variant does exist here: https://github.com/spacekookie/barrel/blob/master/src/lib.rs#L139

It might be as simple of a fix as making sure the right variant is pattern matched against in the `match` block.

**Comment by rippinrobr** [comment]
@ELD yep, you are correct. I didn't look at the code until after I duplicated your issue.  Once I swapped out the match arm and it worked as it should.
